Repository E3SM-Project/mache, pull requests merged in 2024-11, with the labels that each got.

#207 Add support for python 3.13
  .github/workflows/build_workflow.yml
  pyproject.toml
Labels: ci

#209 Fix intel module filepaths on pm-cpu
  mache/spack/pm-cpu_intel_mpich.yaml
Labels: bug, spack

#210 Fix Perlmutter nvidia spack
  mache/spack/pm-cpu_nvidia_mpich.yaml
  mache/spack/pm-gpu_nvidiagpu_mpich.yaml
Labels: bug
