Repository E3SM-Project/mache, pull requests merged in 2024-10, with the labels that each got.

#199 Update pre-commit dependencies
  .pre-commit-config.yaml
Labels: dependencies, ci

#200 Switch pre-commit `autoupdate_schedule` to `weekly`
  .pre-commit-config.yaml
Labels: dependencies, ci

#203 Various fixes to the docs
  docs/conf.py
  pyproject.toml
  spec-file.txt
Labels: bug, documentation, clean-up

#201 Update `chicoma-cpu` modules
  mache/spack/chicoma-cpu_gnu_mpich.csh
  mache/spack/chicoma-cpu_gnu_mpich.sh
  mache/spack/chicoma-cpu_gnu_mpich.yaml
  mache/spack/chicoma-cpu_nvidia_mpich.csh
  mache/spack/chicoma-cpu_nvidia_mpich.sh
  mache/spack/chicoma-cpu_nvidia_mpich.yaml
Labels: spack
