Repository E3SM-Project/mache, pull requests merged in 2024-07, with the labels that each got.

#170 Switch all mamba actions to miniforge/conda
  .github/workflows/build_workflow.yml
Labels: ci

#171 Create documentation
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  docs/.gitignore
  docs/Makefile
  docs/_static/style.css
  docs/_templates/layout.html
  docs/_templates/versions.html
  docs/conf.py
  docs/developers_guide/adding_new_machine.md
  docs/developers_guide/api.md
  docs/developers_guide/building_docs.md
  docs/developers_guide/quick_start.md
  docs/index.md
  spec-file.txt
Labels: documentation

#172 Simplify and update the README
  README.md
Labels: documentation

#173 Update `config_machines.xml` and corresponding files
  mache/cime_machine_config/config_machines.xml
  mache/spack/chrysalis_gnu_openmpi.csh
  mache/spack/chrysalis_gnu_openmpi.sh
  mache/spack/chrysalis_gnu_openmpi.yaml
  mache/spack/chrysalis_intel_impi.csh
  mache/spack/chrysalis_intel_impi.sh
  mache/spack/chrysalis_intel_openmpi.csh
  mache/spack/chrysalis_intel_openmpi.sh
  mache/spack/pm-cpu_gnu_mpich.csh
  mache/spack/pm-cpu_gnu_mpich.sh
  mache/spack/pm-cpu_intel_mpich.csh
  mache/spack/pm-cpu_intel_mpich.sh
  mache/spack/pm-cpu_nvidia_mpich.csh
  mache/spack/pm-cpu_nvidia_mpich.sh
  mache/spack/pm-gpu_gnugpu_mpich.csh
  mache/spack/pm-gpu_gnugpu_mpich.sh
  mache/spack/pm-gpu_nvidiagpu_mpich.csh
  mache/spack/pm-gpu_nvidiagpu_mpich.sh
Labels: spack, config-machines

#177 Update CI and pre-commit for new setup config files
  .github/workflows/build_workflow.yml
  .pre-commit-config.yaml
Labels: ci

#178 Update PR template to add documentation-related checks
  .github/pull_request_template.md
Labels: clean-up

#179 Fix setuptools on conda-forge feedstock
  MANIFEST.in
  conda/meta.yaml
  pyproject.toml
  spec-file.txt
Labels: bug

#184 Omit OMP* environment variables with gnu on chrysalis
  mache/spack/chrysalis_gnu_openmpi.csh
  mache/spack/chrysalis_gnu_openmpi.sh
Labels: bug, spack

#186 Add flynt package to linter
  .pre-commit-config.yaml
  pyproject.toml
  spec-file.txt
Labels: dependencies
