Repository E3SM-Project/mache, pull requests merged in 2025-01, with the labels that each got.

#217 Use separate conda cache directories in CI
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  .github/workflows/pre_commit_update_workflow.yml
Labels: ci

#218 Add back `use_e3sm_hdf5_netcdf` config option
  mache/machines/anvil.cfg
  mache/machines/chicoma-cpu.cfg
  mache/machines/chrysalis.cfg
  mache/machines/compy.cfg
  mache/machines/frontier.cfg
  mache/machines/pm-cpu.cfg
  mache/machines/pm-gpu.cfg
Labels: bug

#219 Allow diags to be synced from LCRC to remote
  docs/developers_guide/quick_start.md
  mache/sync/diags.py
Labels: enhancement

#220 Remove deprecated `install_missing_compilers` spack config
  mache/spack/anvil_gnu_mvapich.yaml
  mache/spack/anvil_gnu_openmpi.yaml
  mache/spack/anvil_intel_impi.yaml
  mache/spack/anvil_intel_mvapich.yaml
  mache/spack/anvil_intel_openmpi.yaml
  mache/spack/chicoma-cpu_gnu_mpich.yaml
  mache/spack/chicoma-cpu_nvidia_mpich.yaml
  mache/spack/chrysalis_gnu_openmpi.yaml
  mache/spack/chrysalis_intel_impi.yaml
  mache/spack/chrysalis_intel_openmpi.yaml
  mache/spack/compy_gnu_openmpi.yaml
  mache/spack/compy_intel_impi.yaml
  mache/spack/frontier_crayclang_mpich.yaml
  mache/spack/frontier_crayclanggpu_mpich.yaml
  mache/spack/frontier_gnu_mpich.yaml
  mache/spack/frontier_gnugpu_mpich.yaml
  mache/spack/pm-cpu_gnu_mpich.yaml
  mache/spack/pm-cpu_intel_mpich.yaml
  mache/spack/pm-cpu_nvidia_mpich.yaml
  mache/spack/pm-gpu_gnugpu_mpich.yaml
  mache/spack/pm-gpu_nvidiagpu_mpich.yaml
Labels: clean-up

#221 Add amdclang support on frontier
  mache/spack/frontier_amdclang_mpich.csh
  mache/spack/frontier_amdclang_mpich.sh
  mache/spack/frontier_amdclang_mpich.yaml
  mache/spack/frontier_amdclanggpu_mpich.csh
  mache/spack/frontier_amdclanggpu_mpich.sh
  mache/spack/frontier_amdclanggpu_mpich.yaml
Labels: enhancement

#222 In CI, update docs build version to 3.13
  .github/workflows/docs_workflow.yml
Labels: ci

#223 Add Mache logo
  README.md
  docs/_static/mache-logo.png
  docs/index.md
Labels: documentation

#225 Remove conda caching in CI
  .github/workflows/build_workflow.yml
Labels: ci

#226 Remove conda caching in the docs workflow
  .github/workflows/docs_workflow.yml
Labels: ci
