Repository E3SM-Project/mache, pull requests merged in 2025-03, with the labels that each got.

#237 Switch to `ruff` for linting with `pre-commit`
  .flake8
  .pre-commit-config.yaml
  docs/developers_guide/quick_start.md
  mache/__init__.py
  mache/__main__.py
  mache/discover.py
  mache/machine_info.py
  mache/permissions.py
  mache/spack/__init__.py
  mache/sync/__init__.py
  mache/sync/diags.py
  pyproject.toml
  spec-file.txt
Labels: documentation, dependencies

#245 Switch CI from miniconda to micromamba
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
Labels: ci

#244 Add `tests` to dirs excluded from package
  pyproject.toml
Labels: bug

#229 Add a utility that shows updates to `config_machines.xml`
  .gitignore
  mache/cime_machine_config/__init__.py
  mache/io.py
  mache/machines/__init__.py
  spec-file.txt
  utils/README.md
  utils/update_cime_machine_config.py
Labels: enhancement
